improves verb reflexivity

diff --git a/build b/build
--- a/build
+++ b/build
@@ -7,6 +7,7 @@ CLEAN_TEMP_DATA=true
 RUN_TESTS=true
 SET_TRAP=true
 COPY_FINAL=true
+SYLLABLE=true
 SLOVNIK_PASS=
 ARCHIVE=
 
@@ -19,50 +20,45 @@ do
 		-ns|--no-slovnik)
 			PROCESS_SLOVNIK=
 			RUN_TESTS=
-			shift;
 		;;
 		-nt|--no-tests)
 			RUN_TESTS=
-			shift;
 		;;
 		-nf|--no-fail)
 			EXIT_ON_FAILURE=
-			shift;
+		;;
+		-nsl|--no-syllable)
+			SYLLABLE=
 		;;
 		-c|--clean)
 			make clean-code
-			shift;
 		;;
 		-d|--debug)
 			CLEAN_TEMP_DATA=
-			shift;
 		;;
 		-nt|--no-trap)
 			SET_TRAP=
-			shift;
 		;;
 		-nc|--no-copy)
 			COPY_FINAL=
-			shift;
 		;;
 		-p|--pass)
 			SLOVNIK_PASS="$2"
-			shift 2;
+			shift;
 		;;
 		-a|--archive)
 			ARCHIVE=true
-			shift;
 		;;
 		--help)
-			echo "./build [--help --no-slovnik --no-tests --no-fail --clean --debug --no-trap --no-copy --archive]"
+			echo "./build [--help --no-slovnik --no-tests --no-fail --no-syllable --clean --debug --no-trap --no-copy --archive]"
 			exit 0;
 		;;
 		*)
 			>&2 echo "Unknown option" $key
-			shift;
 			exit 1;
 		;;
 	esac
+	shift;
 done
 
 if [ $PROCESS_SLOVNIK ] ; then
@@ -330,14 +326,16 @@ fi
 echo Vacuum
 sqlite3 $DB_MAIN_PATH "VACUUM"
 
-echo Create syllable table
-sqlite3 $DB_MAIN_PATH ".read pipeline/90_create_syllable.sql"
+if [ $SYLLABLE ] ; then
+	echo Create syllable table
+	sqlite3 $DB_MAIN_PATH ".read pipeline/90_create_syllable.sql"
 
-echo Generating syllables
-./bin/generate_syllable $DB_MAIN_PATH
+	echo Generating syllables
+	./bin/generate_syllable $DB_MAIN_PATH
 
-echo Vacuum
-sqlite3 $DB_MAIN_PATH "VACUUM"
+	echo Vacuum
+	sqlite3 $DB_MAIN_PATH "VACUUM"
+fi
 
 if [ $COPY_FINAL ] ; then
 	echo Persisting temp database
